Ability to configure Docker daemon options
geerlingguy/ansible-role-docker pull request #92
Opened 2018-10-08 19:12 UTC by Rickkwa

Resolves #90

2018-11-05 16:37 UTC, davidecavestro commented
This patch would also cover #84

2018-12-03 23:03 UTC, varac commented
Hej, what's the state of this PR ? Would love to see it merged soon !

2019-01-25 03:59 UTC, llbbl commented
devicemapper shouldn't be set as default.

https://github.com/docker/cli/pull/1424

2019-03-18 22:27 UTC, boxrick commented
This would also fix some issues I am having, @geerlingguy any chance of a merge?

2019-11-13 06:31 UTC, andrey1vanov commented
@geerlingguy is there any chance that PR will be merged? As this is a really nice feature.

2020-06-09 02:38 UTC, robbyoconnor commented
Please reopen this

2020-06-21 20:52 UTC, robbyoconnor commented
Please reopen this

2020-09-23 20:48 UTC, dr-edmond-merkle commented
I think you need to create the configuration file before the installation of docker in the task? I needed that for this to work for me locally.

2021-01-13 18:26 UTC, geerlingguy requested changes

2021-01-13 18:26 UTC, geerlingguy commented on tasks/main.yml
> +    state: directory
The last thing I'd like to make sure to do is _not_ touch the file if the default (`docker_daemon_options: {}`) is set.

That way (a) existing role users won't have that file wiped out if it currently contains things and they update the role, and (b) people can manage the file on their own simply by _not_ setting the option in this role's vars.

2021-04-16 20:17 UTC, robbyoconnor commented
bump

2021-07-16 17:46 UTC, robbyoconnor commented
bump

2021-07-16 19:57 UTC, geerlingguy commented
Closing in favor of #256, which is based on this.

2021-07-16 19:57 UTC, closed without merging